name: tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Alpine:
    runs-on: ubuntu-latest
    container: python:3.10-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore system dependencies
        id: system-deps-cache
        uses: actions/cache@v3
        with:
          path: |
            dev/deps/alpine.txt
          key: ${{ runner.os }}-system-deps-${{ hashFiles('dev/deps/alpine.txt') }}
          restore-keys: |
            ${{ runner.os }}-system-deps-

      - name: Install system dependencies
        if: steps.system-deps-cache.outputs.cache-hit != 'true'
        run: |
          DEPS=$(cat dev/deps/alpine.txt | tr '\n' ' ')
          apk add --no-cache $DEPS

      - name: Restore virtual environment
        id: venv-cache
        uses: actions/cache@v3
        with:
          path: |
            .venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Setup virtual environment
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip virtualenv
          make venv

      - name: Install dependencies
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          . .venv/bin/activate
          python -m pip install -r requirements/requirements-dev.txt
          python -m pip install -r requirements/requirements.txt
          python -m pip install -r requirements/requirements-django.txt
          python -m pip install -r requirements/requirements-samples.txt

      - name: Link packages
        env:
          CI: true
        run: |
          . .venv/bin/activate
          make link

      - name: Lint
        env:
          CI: true
        run: |
          . .venv/bin/activate
          make typecheck

      - name: Test
        env:
          CI: true
        run: |
          . .venv/bin/activate
          make test
